# Generated by Django 3.2 on 2024-01-09 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=10, verbose_name='类别')),
                ('is_active', models.BooleanField(default=True, verbose_name='假删除')),
            ],
            options={
                'verbose_name': '图书分类',
                'verbose_name_plural': '图书分类',
                'db_table': 'book_type',
            },
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('pressNo', models.CharField(editable=False, max_length=12, unique=True, verbose_name='出版社编号')),
                ('pressTitle', models.CharField(max_length=40, verbose_name='出版社名称')),
                ('address', models.CharField(max_length=40, verbose_name='出版社地址')),
                ('zipCode', models.CharField(max_length=6, verbose_name='邮政编码')),
                ('contactPerson', models.CharField(max_length=12, verbose_name='联系人')),
                ('telephone', models.CharField(max_length=15, verbose_name='联系电话')),
                ('fax', models.CharField(max_length=15, verbose_name='传真')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='假删除')),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
                'db_table': 'press',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('ISBN', models.CharField(max_length=17, unique=True, verbose_name='书籍编号')),
                ('image', models.CharField(max_length=100, verbose_name='图书封面')),
                ('bookTitle', models.CharField(max_length=30, verbose_name='书名')),
                ('author', models.CharField(max_length=40, verbose_name='作者')),
                ('publishDate', models.DateField(verbose_name='出版日期')),
                ('version', models.IntegerField(blank=True, null=True, verbose_name='版次')),
                ('stockNumber', models.IntegerField(default=0, verbose_name='库存数量')),
                ('introduction', models.TextField(max_length=500, verbose_name='内容简介')),
                ('is_active', models.BooleanField(default=True, verbose_name='假删除')),
                ('category', models.ManyToManyField(related_name='category_books', to='book.BookType', verbose_name='书籍分类')),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='press_books', to='book.press', verbose_name='出版社')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'db_table': 'book',
            },
        ),
    ]
