# Generated by Django 3.2 on 2024-01-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='press',
        ),
    ]
