# Generated by Django 3.2 on 2024-01-10 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_press'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='press',
            name='fax',
        ),
        migrations.CreateModel(
            name='BookPress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_press', to='book.book', verbose_name='书籍')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.press', verbose_name='出版社')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
