# Generated by Django 3.2 on 2024-01-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20240110_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookpress',
            options={'verbose_name': '书籍与出版社', 'verbose_name_plural': '书籍与出版社'},
        ),
        migrations.AlterModelTable(
            name='bookpress',
            table='books_press',
        ),
    ]
