# Generated by Django 3.2 on 2024-01-10 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20240110_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='press',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.press', verbose_name='出版社'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='stockNumber',
            field=models.IntegerField(default=0, verbose_name='馆藏数量'),
        ),
        migrations.DeleteModel(
            name='BookPress',
        ),
    ]
