# Generated by Django 3.2 on 2024-01-10 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20240110_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=17, verbose_name='书籍编号'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='book.booktype', verbose_name='类别'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookCategory',
        ),
    ]
