# Generated by Django 3.2 on 2024-01-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20240110_1613'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('ISBN', 'category'), name='unique_ISBN_ISBN'),
        ),
    ]
