# Generated by Django 3.2 on 2024-01-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_unique_isbn_isbn'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='unique_ISBN_ISBN',
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('ISBN', 'bookTitle'), name='unique_ISBN_bookTitle'),
        ),
    ]
