# Generated by Django 3.2 on 2024-01-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20240110_1617'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='unique_ISBN_bookTitle',
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('ISBN', 'category'), name='unique_ISBN_ISBN'),
        ),
    ]
