# Generated by Django 3.2 on 2024-01-10 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0011_auto_20240110_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_return', models.BooleanField(default=False, verbose_name='是否归还')),
                ('return_data', models.DateField(auto_now_add=True, verbose_name='归还日期')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='book.book', verbose_name='借阅图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='借阅人')),
            ],
            options={
                'verbose_name': '图书借阅',
                'verbose_name_plural': '图书借阅',
                'db_table': 'borrow',
            },
        ),
    ]
