# Generated by Django 3.2 on 2024-01-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20240110_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRootType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=10, verbose_name='类别')),
                ('is_active', models.BooleanField(default=True, verbose_name='假删除')),
            ],
            options={
                'verbose_name': '图书一级分类',
                'verbose_name_plural': '图书一级分类',
                'db_table': 'book_root_type',
            },
        ),
        migrations.AlterModelOptions(
            name='booktype',
            options={'verbose_name': '图书二级分类', 'verbose_name_plural': '图书二级分类'},
        ),
    ]
