# Generated by Django 3.2 on 2024-01-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20240113_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktype',
            name='root_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_type', to='book.bookroottype', verbose_name='图书一级分类'),
        ),
    ]
