# Generated by Django 3.2 on 2024-01-13 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_booktype_root_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktype',
            name='root_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second_type', to='book.bookroottype', verbose_name='图书一级分类'),
            preserve_default=False,
        ),
    ]
