# Generated by Django 3.2 on 2024-02-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_bookcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcollection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
