# Generated by Django 3.2 on 2024-03-01 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_bookcollection_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='borrowing_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='借阅日期'),
            preserve_default=False,
        ),
    ]
