# Generated by Django 3.2 on 2024-01-18 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=100, verbose_name='活动主题')),
                ('content', models.TextField(verbose_name='发布内容')),
                ('file', models.JSONField(blank=True, null=True, verbose_name='公告文件')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_notice', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '公告表',
                'verbose_name_plural': '公告表',
                'db_table': 'notice',
            },
        ),
    ]
