# Generated by Django 3.2 on 2024-01-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20240118_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='是否顶置'),
        ),
    ]
