# Generated by Django 3.2 on 2024-04-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_notice_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='公告文件'),
        ),
    ]
