# Generated by Django 3.2 on 2024-04-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_notice_notice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_file',
            field=models.FileField(blank=True, null=True, upload_to='lib_system/notice_file', verbose_name='公告文件'),
        ),
    ]
