# Generated by Django 3.2 on 2024-02-26 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='学院名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '学院表',
                'verbose_name_plural': '学院表',
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='专业名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major', to='school.faculty', verbose_name='学院')),
            ],
            options={
                'verbose_name': '专业表',
                'verbose_name_plural': '专业表',
                'db_table': 'major',
            },
        ),
    ]
