# Generated by Django 3.2 on 2024-01-09 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('student_num', models.CharField(max_length=20, verbose_name='学号')),
                ('openid', models.CharField(db_index=True, default='', max_length=200, verbose_name='用户的openid')),
                ('type', models.CharField(default='', max_length=50, verbose_name='用户角色(学生或教师或校外人员)')),
                ('faculty_code', models.CharField(max_length=30, null=True, verbose_name='院系代码')),
                ('faculty_title', models.CharField(max_length=50, null=True, verbose_name='院系名')),
                ('realname', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('is_active', models.BooleanField(default=True, verbose_name='账号是否启用')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否能登陆到后台')),
                ('can_login_system', models.BooleanField(default=True, verbose_name='是否能登陆系统')),
                ('status', models.CharField(default='', max_length=50, verbose_name='状态')),
                ('grade_name', models.CharField(default='', max_length=200, verbose_name='所在年级名称')),
                ('major_code', models.CharField(default='', max_length=30, verbose_name='专业号')),
                ('major_title', models.CharField(default='', max_length=50, verbose_name='专业名称')),
                ('class_code', models.CharField(default='', max_length=30, verbose_name='班级号')),
                ('class_title', models.CharField(default='', max_length=50, verbose_name='班级名称')),
                ('wechat_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='微信号')),
                ('sex', models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='性别')),
                ('wx_photo', models.CharField(blank=True, default='', max_length=350, null=True, verbose_name='微信头像')),
                ('photo', models.ImageField(default='', upload_to='club_system/account_photo/', verbose_name='头像')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '账号表',
                'verbose_name_plural': '账号表',
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='MiniprogramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('mini_program_openid', models.CharField(db_index=True, max_length=100, verbose_name='微信小程序用户的openid')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联账号')),
            ],
            options={
                'verbose_name': '微信小程序用户',
                'verbose_name_plural': '微信小程序用户',
                'db_table': 'mini_program_account',
            },
        ),
    ]
