# Generated by Django 3.2 on 2024-01-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(default='', upload_to='account_photo/', verbose_name='头像'),
        ),
    ]
