# Generated by Django 3.2 on 2024-02-19 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniprogramaccount',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联账号'),
        ),
    ]
