# Generated by Django 3.2 on 2024-02-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20240219_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='wx_photo',
            field=models.CharField(blank=True, default='lib_system/wx_photo/216-20240224170703-defalt_avar.png', max_length=350, null=True, verbose_name='微信头像'),
        ),
    ]
