# Generated by Django 3.2 on 2024-04-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_wx_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='class_title',
        ),
        migrations.RemoveField(
            model_name='account',
            name='wechat_code',
        ),
    ]
