# Generated by Django 3.2 on 2024-04-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20240414_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='account_photo/', verbose_name='头像'),
        ),
    ]
