# Generated by Django 3.2 on 2024-03-02 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0002_rename_article_comment_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpttComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(verbose_name='评论内容')),
                ('is_active', models.BooleanField(default=True)),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_mptt_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='all_mptt_comments', to='message.bookmessagetheme', verbose_name='评论文章')),
                ('pre_comment', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='message.mpttcomment', verbose_name='父评论id')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replyers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
