# Generated by Django 3.2 on 2024-03-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20240302_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpttcomment',
            old_name='pre_comment',
            new_name='parent',
        ),
    ]
