# Generated by Django 3.2 on 2024-04-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_alter_mpttcomment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_comments', to='message.bookmessagetheme', verbose_name='评论文章'),
        ),
    ]
