# Generated by Django 3.2 on 2024-04-18 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0007_alter_comment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmessagetheme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_message', to=settings.AUTH_USER_MODEL, verbose_name='发起人'),
        ),
    ]
