# Generated by Django 3.2 on 2024-03-11 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('seat_number', models.CharField(max_length=20, verbose_name='座位编号')),
                ('floor', models.PositiveIntegerField(default=1, verbose_name='楼层（数据字典中的lib_floor）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '座位表',
                'verbose_name_plural': '座位表',
                'db_table': 'seat',
            },
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('period', models.PositiveIntegerField(default=1, verbose_name='楼层（数据字典中的reservation_period）')),
                ('appointment_date', models.DateField(auto_now_add=True, verbose_name='预约日期')),
                ('use_time', models.DateTimeField(null=True, verbose_name='使用时间')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservation', to='reservation.seat', verbose_name='预约座位')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_reservation', to=settings.AUTH_USER_MODEL, verbose_name='预约人')),
            ],
            options={
                'verbose_name': '座位预约表',
                'verbose_name_plural': '座位预约表',
                'db_table': 'reservation',
            },
        ),
    ]
