# Generated by Django 3.2 on 2024-03-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='period',
            field=models.PositiveIntegerField(verbose_name='楼层（数据字典中的reservation_period）'),
        ),
    ]
