# Generated by Django 3.2 on 2024-04-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='floor',
            field=models.PositiveIntegerField(default=1, verbose_name='楼层（数据字典中的lib_floor,数值为当前小时-8）'),
        ),
    ]
