# Generated by Django 3.2 on 2024-04-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_seat_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='period',
            field=models.PositiveIntegerField(verbose_name='楼层（数据字典中的reservation_period，数值为当前小时-8）'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='floor',
            field=models.PositiveIntegerField(default=1, verbose_name='楼层（数据字典中的lib_floor,0表-1，以此类推）'),
        ),
    ]
