# Generated by Django 3.2 on 2024-04-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20240411_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='floor',
            field=models.PositiveIntegerField(default=1, verbose_name='楼层（数据字典中的lib_floor,0表负一楼，以此类推）'),
        ),
    ]
