# Generated by Django 3.2 on 2024-04-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_seat_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='period',
            field=models.PositiveIntegerField(verbose_name='时间段（数据字典中的reservation_period，数值为当前小时-8）'),
        ),
    ]
